### ISSUE TITLE
エンジニアリングマネージャーのしごと読書会

### ISSUE THREAD

**Issue by hiromitsuuuuu** [neotag/riakuto#114]
を読む。

**Comment by hiromitsuuuuu** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを３章まで読んだ

##  次回やること
- ４章から読む

## 次回日程
- 10月15日（土）19:30〜21:30

**Comment by okachaang** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを５章まで読んだ

##  次回やること
- ６章から読む

## 次回日程
- 11月12日（土）19:00〜20:20

**Comment by okachaang** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを６章まで読んだ

##  次回やること
- ７章から読む

## 次回日程
- 11月26日（土）19:30〜21:30

**Comment by neotag** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを7章まで読んだ

##  次回やること
- 8章から読む

## 次回日程
- 12月24日（土）14:30〜16:30

**Comment by hiromitsuuuuu** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを8章〜10章まで読んだ

##  次回やること
- 11章から読む

## 次回日程
- 1月14日（土）19:30～21:30

**Comment by hiromitsuuuuu** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを11章〜13章まで読んだ

##  次回やること
- 14章から読む

## 次回日程
- 1月21日（土）19:30～21:30

**Comment by hiromitsuuuuu** [comment]
## やったこと
- エンジニアリングマネージャーのしごとを14章〜15章まで読んだ

##  次回やること
- 16章から読む（できれば18章まで読めると嬉しい

## 次回日程
- 2月18日（土）19:30～21:30

**Comment by hiromitsuuuuu** [comment]
エンジニアリングマネージャーのしごとを読みきった！！
次は、HighOutputManagementを読むぞ！

## 次回日程
- 3月18日（土）19:30～21:30

**Comment by neotag** [comment]
エンジニアリングマネージャーのしごと読了したのでクローズ
