### ISSUE TITLE
HIGH OUTPUT MANAGEMENT読書会

### ISSUE THREAD

**Issue by hiromitsuuuuu** [neotag/riakuto#128]
を読む！

**Comment by hiromitsuuuuu** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT 2章まで読んだ

##  次回やること
- 3章から読む

## 次回日程
- 4月8日（土）19:30〜21:30

**Comment by okachaang** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT 3章まで読んだ

##  次回やること
- 4章から読む

## 次回日程
- 4月15日（土）19:30〜21:30

**Comment by okachaang** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT 4章まで読んだ

##  次回やること
- 5章から読む

## 次回日程
- 4月29日（土）19:30〜21:30

**Comment by hiromitsuuuuu** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT ６章まで読んだ

##  次回やること
- ７章から読む

## 次回日程
- 5月27日（土）19:30〜21:30

**Comment by okachaang** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT １０章まで読んだ

##  次回やること
- １１章から読む

## 次回日程
- 6月11日（日）19:30〜21:30

**Comment by okachaang** [comment]
## やったこと
- HIGH OUTPUT MANAGEMENT １２章まで読んだ

##  次回やること
- １３章から読む

## 次回日程
- 6月24日（土）19:30〜21:30

**Comment by hiromitsuuuuu** [comment]
読み切った！ので、次回は次の本を選定するところから。

次回日程
７月22日（土）19:30〜21:30
