### ISSUE TITLE
PMBOKガイド読書会

### ISSUE THREAD

**Issue by hiromitsuuuuu** [neotag/riakuto#89]
PMBOKガイド７版を読む会

**Comment by hiromitsuuuuu** [comment]
## やったこと
- PM標準の2.3まで読んだ

##  次回やること
- 2.4から読みすすめる（6までいけると、２回で読み切れて良さそう）

## きになったこと
- ポートフォリオとプログラムの粒度がどんなものなのか想像できてない
- プログラムマネジメント標準、ポートフォリオマネジメント標準ってなんだろ

## 次回日程
- 1月23日（日）16時〜18時

**Comment by neotag** [comment]
## やったこと
- PM標準の 2.4 から 3.5 まで読んだ

##  次回やること
- 3.6から読みすすめる（次回はプロジェクトマネジメント標準 全部読めそう P.60）

## 気になったこと
- オーナーシップ・スチュワードシップ・リーダーシップの話で盛り上がった
- プロダクトマネジメントの知識体系ガイドがあるらしいが ProdBOK のこと？
- システム思考面白そう
  この本が良いらしい https://www.amazon.co.jp/dp/4492555757
- 価値工学 VE が気になる
  https://engineer.fabcross.jp/archeive/190327_value-engineering.html

## 次回日程
- 2月19日（土）16時〜18時

**Comment by hiromitsuuuuu** [comment]
## やったこと
- PM標準の最後まで読み切った

##  次回やること
- 知識体系ガイドの最初から読み進める（読み方は今まで通りの形式）

## 気になったこと
- [組織のチェンジマネジメント：実務ガイド](https://www.pmi-japan.shop/shopdetail/000000000007/)が気になる
- ７版対応の本が出始めている
　- https://www.shoeisha.co.jp/book/detail/9784798172422
　- https://www.shoeisha.co.jp/book/detail/9784798169590

## 次回日程
- 3月5日（土）16時〜18時

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 知識体系ガイドの2.2.3 まで読んだ

##  次回やること
- 知識体系ガイドの2.2.4から読む

## 気になったこと
- ネトフリの人事本がいいらしい
    - https://www.amazon.co.jp/dp/4334962211

## 次回日程
- 3月19日（土）20時〜22時

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 知識体系ガイドの2.3.3 まで読んだ

##  次回やること
- 知識体系ガイドの2.3.4から読む

## 気になったこと
- ソーシャル認識の文脈で「LISTEN」という本をneotagさんに教えてもらった
    - https://www.amazon.co.jp/dp/B099582LR7

## 次回日程
- 4月2日（土）16時〜18時

**Comment by neotag** [comment]
## やったこと
- 知識体系ガイドの2.4.2 まで読んだ

##  次回やること
- 知識体系ガイドの2.4.3から読む

## 気になったこと
- 今日はとくになし

## 次回日程
- 4月16日（土）16時〜18時

**Comment by neotag** [comment]
## やったこと
- 知識体系ガイドの2.4.11 まで読んだ

##  次回やること
- 知識体系ガイドの2.5から読む

## 気になったこと
- 今日はとくになし

## 次回日程
- 5月14日（土）16時〜18時

**Comment by hiromitsuuuuu** [comment]
ムードボードのところで出てきたふりかえりTips
- Keepで観察し、Problemで裏付けをする、１on１で深堀りする
- Keepは褒め合いという位置づけで出してもらう（いっぱいいっぱいだと人を褒める余裕がなくなっちゃう）
- エクスキューズは吐き出させておく
- その次に「どうですかね、チームとして困ることありそうですか？」
- それでも個人の話しかできないひともいるので、１on１で話したりする
- 重いProblemを上げてくれたひとを褒める

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 知識体系ガイドの2.7.2 まで読んだ

##  次回やること
- 知識体系ガイドの2.7.3から読む

## 気になったこと
ムードボードのところで出てきたふりかえりTips
- Keepで観察し、Problemで裏付けをする、１on１で深堀りする
- Keepは褒め合いという位置づけで出してもらう（いっぱいいっぱいだと人を褒める余裕がなくなっちゃう）
- エクスキューズは吐き出させておく
- その次に「どうですかね、チームとして困ることありそうですか？」
- それでも個人の話しかできないひともいるので、１on１で話したりする
- 重いProblemを上げてくれたひとを褒める

## 次回日程
- 5月29日（日）11:30〜13:30

**Comment by neotag** [comment]
## やったこと
- 知識体系ガイドの 3.3.5 まで読んだ

##  次回やること
- 知識体系ガイドの 3.4 から読む

## 次回日程
- 6月11日（日）16:00〜18:00

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 知識体系ガイドの 4.3. まで読んだ

##  次回やること
- 知識体系ガイドの 4.4 から読む

## 次回日程
- 7月9日（土）16:00〜18:00

**Comment by neotag** [comment]
## やったこと
- 知識体系ガイドの付属文章 X4 まで読んだ

##  次回やること
- 知識体系ガイドの付属文章 X5 を読む
- 図解即戦力　PMBOK第6版の知識と手法がこれ1冊でしっかりわかる教科書 を読み始めてみる

## 次回日程
- 7月23日（土）19:30〜21:30

**Comment by neotag** [comment]
## やったこと
- 知識体系ガイドの付属文章 X5 読んだ。これで第7版読了
    - 用語集は読まなかったけど、それぞれ自習したら新たな発見がありそう
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を1章06まで読んだ

##  次回やること
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を1章06から読む
    - 次回で2章まで読み切れそう

## 次回日程
- 8月6日（土）19:30〜21:30

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を４章まで読んだ
    - 割と黙々と読んだ

##  次回やること
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を５章から読む

## 次回日程
- 8月20日（土）19:30〜21:30　※要日程調整

**Comment by neotag** [comment]
## やったこと
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を５章まで読んだ
    - 割と黙々と読んだ

##  次回やること
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を６章から読む

## 次回日程
- 8月10日（土）20:00〜22:00　※要日程調整

**Comment by hiromitsuuuuu** [comment]
## やったこと
- 図解即戦力 PMBO 第6版の知識と手法が【略】教科書 を読了！！
    - さらっと入門するにはいい本だった！

##  次回やること
- エンジニアリングマネージャーのしごとを読み始める

## 次回日程
- 10月1日（土）19:30〜21:30

**Comment by neotag** [comment]
PMBOK ガイドと図解即戦力 PMBOK 読了したのでクローズ
