### ISSUE TITLE
りあクト！を全部読む

### ISSUE THREAD

**Issue by neotag** [neotag/riakuto#9]
4/1 20:00 から。
7章読み合わせしながら、VS Code の Live share を使ってサンプルコードとか動かしてみる。

**Comment by hiromitsuuuuu** [comment]
読みました！
サンプルコード回りで手を動かす件、↓はどうでしょう？

2～4はお手本なしでペアプロしてみると理解が進みそうなのでやってみたいです。

- [x] Live Shareを確認しながらLintとPrettierの環境整える
- [x] 7-2Propsをコンポーネントに受け渡す」のキャラクター一覧のコンポーネント
- [ ] 「7-3コンポーネント内部の～」のカウンターのコンテナ
- [ ] 「7-4コンポーネントのライフサイクル」のタイマーのコンテナ

**Comment by neotag** [comment]
そうしましょう！初 Live Share

**Comment by hiromitsuuuuu** [comment]
次回は、
-  7-2Propsをコンポーネントに受け渡す」のキャラクター一覧のコンポーネントの、コードを書いてみるところからはじめる。
- お手本のディレクトリでやる。
- LiveShareは、エディタを開いている人が、zoomの画面もシェアする
- 02-propsのディレクトリでLiveShareする（コードを書きたいディレクトリでやる）

**Comment by Morikawa-H5** [comment]
## 今日やったこと
- 7-2のpropsの写経をやった
- 7-3を読み合わせした

## 次にやること
- 7-3のLocalStateを写経する
- 7-4のライフサイクルを読む
- 7-4の写経をする

**Comment by neotag** [comment]
VSCode Live Share + Zoom の画面乗っ取り（謎）が便利でした。

**Comment by hiromitsuuuuu** [comment]
## 今日やったこと
- 7-3のLocalStateを写経する
- 7-4のライフサイクルを読む
- 7-5,6を読む

## 次にやること
- 7-4の写経をする
- 過去やったやつを関数コンポーネントに書き換える
- 7-4のTimerで、Presentational Component / Container Componentの切り分けをやってみる

**Comment by Morikawa-H5** [comment]
## 今日やったこと
- 7-4の写経をする
- 7-4のTimerアプリで、一部だけ（Timerコンポーネント）関数コンポーネントに切り分ける
    -  propsで、timerLeftとリセットの関数を受け取るpresentational Componentに
- さらにコンポーネントを切り分け、contaner Component 化しました

## 次にやること
- 8-4までの読み合わせと写経（おそらく8-3,8-4が実装）
- Gitにコミットしてみる
- ドライバーを交代する

## 今日のコツ
- 写経する時は、実装したい関数がやりたいことをコメントとして残すとよさそう
- 相手のlocal hostが見えるよ。localhost:3000 が相手と同時に見えるよ。こわい。

**Comment by hiromitsuuuuu** [comment]
## 今日やったこと
- 8-4までの読み合わせと実装
- 8-5,6の読み合わせ（8-5は写経なし）
- 9-1~3の読み合わせ

## 次にやること
- 9章のReact Routerを実装してみる（どんなデータ構造で何をやるかは要相談）
- Routingは一緒に開発し、各ページを各々で実装する（プルリクベース）
    - 3ページに分けて、ホーム/一覧/詳細スタイルにしていいかも
- 10-1~3まで読む（3の途中で時間切れになりそう）

## 次回日程
- 5/2（土）15:30-17:30
    - GW中に10章を終え（写経までする）られれるとよさそう

**Comment by hiromitsuuuuu** [comment]
## 今日やったこと
- 9章のReact Routerを実装してみた（簡易的な要点を抑えた）
- 10-1~3まで読んだ

## 次にやること
- 10-3 の写経をやる
    - 前提条件：関数コンポーネント化したカウントアプリの状態からRedux導入する
    - create react app の初期状態からはじめる（辛くなったら出来合いものをパクる）
    - 写経する → 開発者視点から見た、コードの役割を図解する（どこで何をやっているかわかるように。そのあとブログにもできる）
- 10-4を読む（写経はしない）

##  次回日程
- 5/6（水）14:00-17:00

**Comment by hiromitsuuuuu** [comment]
## 今日やったこと
- 10-3 の写経をやった
    - 前提条件：関数コンポーネント化したカウントアプリの状態からRedux導入する
    - create react app の初期状態からはじめた

### 積み残し
- [x] 開発者視点から見た、コードの役割を図解する（どこで何をやっているかわかるように。そのあとブログにもできる）
- [x] 10-4を読む ※知識として知っておけばいいレベルなので読み合わせは飛ばした

## 次にやること
- [x] 11-1~11-2までを読む（調子がよければ11-3までを読む）

##  次回日程
- 5/13（水）20:30-22:00

**Comment by neotag** [comment]
次回メモ：↓のコミットからファイルをパクってスタートする
https://github.com/neotag/riakuto/pull/20/commits/bd09b5ac6b7d8cfad1fcb72dc57faf63f5ff644f

**Comment by hiromitsuuuuu** [comment]
## 今日やったこと
- 11-1~11-3までを読んだ

## 次にやること
- [x] 11-3を写経する
- [x] create-react-app からやる
    - 前回のlint類を用意したところをコピる

## 次回日程
- 5月20日（水）20:30-22:00

**Comment by neotag** [comment]
本がおわったらやってみたいこと

- RealWorld を react/redux/redux-saga 構成でやってみる
  - https://github.com/gothinkster/realworld
  - 古いけど参考： https://github.com/gothinkster/react-redux-realworld-example-app
- Product Backlog でその日にやること管理

**Comment by neotag** [comment]
## 今日やったこと
- 11-3 redux-saga を create-react-app から初めて一通り写経した

## 次にやること
RealWorld を react/redux/redux-saga 構成でやってみる
https://github.com/neotag/riakuto/issues/22#issuecomment-631498881

## 次回日程
- 5月27日（水）20:30-22:00
